name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: 3.12.8/docker
      run: docker build . --file Dockerfile --tag happykhan/amrfinder:amrfinder-1.0.0-base
